import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const read = name => JSON.parse(fs.readFileSync(path.join(root, '_content', `${name}.json`), 'utf8'));
const site = read('site'), projects = read('projects'), news = read('news'), legacy = read('legacy');
const dimensions = read('media-dimensions');
const game = projects.find(p => p.kind === 'flagship');
const routes = [];
const esc = value => String(value ?? '').replace(/[&<>"']/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[c]);
const json = value => JSON.stringify(value).replace(/</g, '\\u003c');
const arrow = '<span aria-hidden="true">↗</span>';
const btn = (href, label, secondary = false) => `<a class="button${secondary ? ' secondary' : ''}" href="${esc(href)}">${esc(label)}${arrow}</a>`;
const link = (href, label) => `<a class="text-link" href="${esc(href)}">${esc(label)}${arrow}</a>`;
const eyebrow = text => `<p class="eyebrow">${esc(text)}</p>`;
const date = item => item.date ? `<time datetime="${esc(item.date)}">${new Date(`${item.date}T12:00:00Z`).toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric', timeZone: 'UTC' })}</time>` : '<span>Undated archive entry</span>';
function brand() {
  // Exact owner artwork. The DG-only export is used at compact header widths.
  return `<a class="brand" href="/" data-brand-slot="full-logo">${site.brand.fullLogo ? `<picture>${site.brand.mark ? `<source media="(max-width:600px)" srcset="${esc(site.brand.mark)}">` : ''}<img src="${esc(site.brand.fullLogo)}" width="640" height="320" alt="Dawn Games LLC"></picture>` : '<span class="brand-name">DAWN GAMES <span class="brand-sub">INDEPENDENT GAME STUDIO</span></span>'}<span class="sr-only"> — Home</span></a>`;
}
function header(active) {
  const items = [['/', 'Home'], ['/games/', 'Games'], ['/about/', 'About'], ['/news/', 'News'], ['/contact/', 'Contact']];
  return `<a class="skip-link" href="#main">Skip to content</a><header class="site-header"><div class="nav-shell">${brand()}<button class="menu-toggle" type="button" aria-label="Open menu" aria-controls="primary-nav" aria-expanded="false"><span class="menu-lines" aria-hidden="true"></span><span>Menu</span></button><nav id="primary-nav" aria-label="Main navigation">${items.map(([url, name]) => `<a href="${url}"${active === name ? ' aria-current="page"' : ''}>${name}</a>`).join('')}<a class="nav-cta" href="/games/dawn-upon-us/">Dawn Upon Us ${arrow}</a></nav></div></header>`;
}
function footer() {
  return `<footer class="site-footer" id="footer"><div class="container footer-top"><div>${brand()}<p>Independent by nature.<br>Worlds built with intent.</p></div><nav aria-label="Footer navigation"><a href="/games/">Games</a><a href="/about/">The studio</a><a href="/news/">News & updates</a><a href="/projects/">Apps & experiments</a><a href="/contact/">Contact</a></nav><div class="footer-connect">${eyebrow('Stay in the loop')}<a href="${esc(site.discord)}" target="_blank" rel="noopener noreferrer">Join our Discord ${arrow}<span class="sr-only"> (opens in a new tab)</span></a><a href="mailto:${esc(site.email)}">Email the studio ${arrow}</a></div></div><div class="container footer-bottom"><small>© 2026 Dawn Games LLC. All rights reserved.</small><a href="/privacy.html">Privacy</a><a href="#top">Back to top ↑</a></div></footer>`;
}
function page({ route, title, description, active = '', body, css = '', noindex = false, article = null, hero = false }) {
  const canonical = `${site.origin}${route}`;
  const schema = article ? { '@context': 'https://schema.org', '@type': 'Article', headline: article.title, ...(article.date ? { datePublished: article.date } : {}), author: { '@type': 'Organization', name: site.company }, publisher: { '@type': 'Organization', name: site.company }, url: canonical } : { '@context': 'https://schema.org', '@type': route === '/' ? 'Organization' : 'WebPage', name: route === '/' ? site.company : title, url: canonical, description, ...(route === '/' ? { email: site.email, sameAs: [site.discord] } : {}) };
  const html = `<!doctype html>
<html lang="en"><head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="theme-color" content="#050505"><meta name="referrer" content="strict-origin-when-cross-origin">
<title>${esc(title)}</title><meta name="description" content="${esc(description)}"><link rel="canonical" href="${canonical}">
${noindex ? '<meta name="robots" content="noindex,follow">' : ''}
<meta property="og:type" content="${article ? 'article' : 'website'}"><meta property="og:site_name" content="Dawn Games">
<meta property="og:title" content="${esc(title)}"><meta property="og:description" content="${esc(description)}"><meta property="og:url" content="${canonical}">
<meta property="og:image" content="${site.origin}/og-image.png"><meta property="og:image:width" content="1200"><meta property="og:image:height" content="630"><meta property="og:image:alt" content="Dawn Games — Independent game studio. Worlds worth surviving.">
<meta name="twitter:card" content="summary_large_image"><meta name="twitter:title" content="${esc(title)}"><meta name="twitter:description" content="${esc(description)}"><meta name="twitter:image" content="${site.origin}/og-image.png">
<link rel="icon" href="${esc(site.brand.favicon)}" sizes="any"><link rel="apple-touch-icon" href="/apple-touch-icon.png"><link rel="manifest" href="/site.webmanifest">
${hero ? `<link rel="preload" as="image" href="${esc(site.hero.image)}" imagesrcset="/assets/media/dawn-world-640.webp 640w, ${esc(site.hero.image)} 1021w" imagesizes="100vw">` : ''}
<link rel="stylesheet" href="/assets/css/site.css"><noscript><link rel="stylesheet" href="/assets/css/no-script.css"></noscript>${css ? `<style>${css}</style>` : ''}
<script type="application/ld+json">${json(schema)}</script><script src="/assets/js/site.js" defer></script></head>
<body id="top">${header(active)}<main id="main" tabindex="-1">${body}</main>${footer()}
<dialog class="lightbox" aria-labelledby="lightbox-caption"><button class="lightbox-close" type="button" aria-label="Close gallery">Close ×</button><figure><img alt="" width="1021" height="705"><figcaption id="lightbox-caption"></figcaption></figure><div class="lightbox-controls"><button type="button" data-gallery-prev aria-label="Previous image">← Previous</button><span class="gallery-count" aria-live="polite"></span><button type="button" data-gallery-next aria-label="Next image">Next →</button></div></dialog>
</body></html>`;
  const output = route === '/' ? 'index.html' : route.endsWith('.html') ? route.slice(1) : `${route.slice(1)}index.html`;
  fs.mkdirSync(path.dirname(path.join(root, output)), { recursive: true });
  const sizedHtml = html.replace(/<img\b[^>]*>/g, tag => {
    const src = tag.match(/src="([^"]+)"/)?.[1];
    if (!src || /\bwidth=/.test(tag)) return tag;
    const size = dimensions[src.startsWith('/') ? src : `/${src}`];
    return size ? tag.replace('<img ', `<img width="${size[0]}" height="${size[1]}" `) : tag;
  });
  fs.writeFileSync(path.join(root, output), sizedHtml.replace(/[\t ]+$/gm, '') + '\n');
  if (!noindex) routes.push(route);
}
const heroImage = () => `<div class="hero-media"><picture><source srcset="/assets/media/dawn-world-640.webp 640w, ${esc(site.hero.image)} 1021w" sizes="100vw" type="image/webp"><img src="${esc(site.hero.image)}" alt="${esc(site.hero.alt)}" width="1021" height="708" fetchpriority="high"></picture>${site.hero.video ? `<video muted loop playsinline preload="none" poster="${esc(site.hero.videoPoster || site.hero.image)}" data-ambient-video><source src="${esc(site.hero.video)}" type="video/mp4"></video><button type="button" class="video-toggle">Play background video</button>` : ''}</div>`;
function heroHome() {
  return `<section class="hero home-hero">${heroImage()}<div class="container hero-content">${eyebrow('Independent game studio')}<h1>WE BUILD<br>WORLDS WORTH<br><span>SURVIVING.</span></h1><p class="hero-copy">Independent game studio creating immersive,<br class="desktop-break"> realistic experiences.</p><div class="actions">${btn(game.path, 'Explore Dawn Upon Us')}${btn('/about/', 'About the studio', true)}</div></div><div class="hero-bottom container"><a class="scroll-cue" href="#flagship"><span aria-hidden="true">↓</span> Discover what’s next</a><span class="media-credit">${esc(site.hero.caption)}</span></div></section>`;
}
function info() {
  return `<dl class="game-facts"><div><dt>Genre</dt><dd>${esc(game.genre)}</dd></div><div><dt>Status</dt><dd><span class="status-dot" aria-hidden="true"></span>${esc(game.status)}</dd></div><div><dt>Engine</dt><dd>${esc(game.engine)}</dd></div><div><dt>World</dt><dd>${esc(game.world)}</dd></div></dl>`;
}
function flagship(compact = false) {
  return `<section class="section flagship" id="flagship"><div class="container"><div class="section-top">${eyebrow('Flagship project')}<span class="status"><span class="status-dot" aria-hidden="true"></span> In development</span></div><div class="flagship-layout"><div class="flagship-copy"><h2>DAWN<br>UPON US<span class="orange">.</span></h2><p class="lead">A world worth exploring.<br>A future worth fighting for.</p><p>${esc(game.description)}</p>${link(game.path, 'Enter the world')}</div><a class="feature-image" href="${game.path}" aria-label="World concept art — Explore Dawn Upon Us"><img src="${esc(game.image)}" srcset="/assets/media/dawn-world-640.webp 640w, ${esc(game.image)} 1021w" sizes="(max-width: 800px) 100vw, 60vw" alt="Dawn Upon Us occupied-city concept artwork, not gameplay" width="1021" height="705" loading="lazy"><span class="image-label">WORLD CONCEPT ART <span aria-hidden="true">↗</span></span></a></div>${compact ? '' : info()}</div></section>`;
}
function principles() {
  return `<div class="principles"><article><span class="principle-rule" aria-hidden="true"></span><h3>Immersion</h3><p>Worlds should feel believable. Atmosphere and detail make a place worth exploring.</p></article><article><span class="principle-rule" aria-hidden="true"></span><h3>Player freedom</h3><p>Give players room to approach situations their way. Leave space for curiosity.</p></article><article><span class="principle-rule" aria-hidden="true"></span><h3>Iteration</h3><p>Build, test, improve. Better experiences come from thoughtful work, one pass at a time.</p></article></div>`;
}
function studio() {
  return `<section class="section studio-section" id="studio"><div class="container"><div class="studio-layout"><div>${eyebrow('About Dawn Games')}<h2>INDEPENDENT<br>BY NATURE.<br><span class="muted">AMBITIOUS<br>BY DESIGN.</span></h2></div><div class="studio-copy"><p class="lead">Small studio.<br>Room for a bigger world.</p><p>Dawn Games LLC is an independent game development studio focused on building immersive digital experiences with an emphasis on atmosphere, exploration and player freedom.</p><p>Our focus today is Dawn Upon Us. Our earlier games and digital projects are part of the journey that brought us here.</p>${link('/about/', 'Meet the studio')}</div></div>${principles()}</div></section>`;
}
function projectCards(list = projects.filter(p => p.kind !== 'flagship').slice(0, 3)) {
  return `<div class="project-grid">${list.map(p => `<article class="project-card"><div class="project-icon">${p.icon ? `<img src="${esc(p.icon)}" alt="${esc(p.title)} app icon" width="80" height="80" loading="lazy">` : `<span aria-hidden="true" class="project-initial">${esc(p.title[0])}</span>`}<span class="caption">${esc(p.label)}</span></div><h3><a href="${p.path}">${esc(p.title)} ${arrow}</a></h3><p>${esc(p.description)}</p></article>`).join('')}</div>`;
}
function portfolio() {
  return `<section class="section"><div class="container"><div class="section-heading"><div>${eyebrow('Apps & experiments')}<h2>EVERY PROJECT<br>BUILDS THE NEXT.</h2></div><p class="section-intro">Smaller games and digital ideas.<br>Still part of our story.</p></div>${projectCards()}<div class="section-end">${link('/projects/', 'Explore all projects')}</div></div></section>`;
}
function newsCards(list = news.slice(0, 2)) {
  if (!list.length) return `<div class="empty-state"><h3>The next chapter is in the making.</h3><p>Development updates and studio news will appear here when there’s something to share.</p></div>`;
  return `<div class="news-grid">${list.map(item => `<article class="news-card"><div class="news-meta"><span>${esc(item.category)}</span>${date(item)}</div><h3><a href="/news/${esc(item.slug)}/">${esc(item.title)} ${arrow}</a></h3><p>${esc(item.summary)}</p><span class="caption">${esc(item.game || site.name)} · ${item.archived ? 'Development archive' : 'Studio update'}</span></article>`).join('')}</div>`;
}
function updates() {
  return `<section class="section updates"><div class="container"><div class="section-heading"><div>${eyebrow('From the development archive')}<h2>THE WORK<br>BEHIND THE WORLD.</h2></div>${link('/news/', 'All updates')}</div>${newsCards()}</div></section>`;
}
function contactBand() {
  return `<section class="contact-band"><div class="container"><div>${eyebrow('Let’s talk')}<h2>GOOD THINGS<br>START WITH A CONVERSATION.</h2></div>${btn('/contact/', 'Get in touch')}</div></section>`;
}
function intro(label, title, description) {
  return `<section class="page-intro container">${eyebrow(label)}<h1>${title}</h1><p class="lead">${esc(description)}</p></section>`;
}
function gallery() {
  return `<section class="section" id="gallery"><div class="container"><div class="section-heading"><div>${eyebrow('Visual development')}<h2>A GLIMPSE<br>OF THE WORLD.</h2></div><p class="section-intro">Concept and world artwork.<br>These images are not gameplay captures.</p></div><div class="gallery-grid">${game.gallery.map((img, i) => `<figure class="gallery-item${i === 0 ? ' gallery-feature' : ''}"><a class="gallery-trigger" href="${esc(img.src)}" data-gallery="dawn-upon-us" data-caption="${esc(img.caption)} — ${esc(img.kind)}" data-alt="${esc(img.alt)}" aria-label="Open ${esc(img.caption)} artwork"><img src="${esc(img.thumbnail)}" width="${img.width}" height="${img.height}" alt="${esc(img.alt)}" loading="lazy"><span class="gallery-expand" aria-hidden="true">↗</span></a><figcaption><span>${esc(img.caption)}</span><small>${esc(img.kind)}</small></figcaption></figure>`).join('')}</div></div></section>`;
}
function developmentNote() {
  return `<aside class="development-note"><span class="status-dot" aria-hidden="true"></span><div><h2>Currently in development</h2><p>Dawn Upon Us is an active project. Visuals, gameplay and the scope of the world may change throughout development. Release details will be shared when confirmed.</p></div></aside>`;
}

page({ route: '/', title: 'Dawn Games | Independent Game Studio', description: 'Dawn Games LLC is an independent game studio creating immersive games and digital experiences. Discover Dawn Upon Us, currently in development.', active: 'Home', hero: true, body: heroHome() + flagship() + studio() + updates() + portfolio() + contactBand() });
page({ route: '/games/', title: 'Games | Dawn Games', description: 'Explore Dawn Upon Us, the flagship open-world tactical project in development at Dawn Games, and discover our earlier games.', active: 'Games', body: intro('Our games', 'WORLDS TO<br>GET LOST IN<span class="orange">.</span>', 'From small, focused challenges to an ambitious open world. This is what we’re building.') + flagship() + `<section class="section"><div class="container"><div class="section-heading"><div>${eyebrow('Earlier games')}<h2>SMALLER WORLDS.<br>SAME CURIOSITY.</h2></div></div>${projectCards(projects.filter(p => p.kind === 'game'))}</div></section>` + contactBand() });
page({ route: game.path, title: 'Dawn Upon Us | In Development · Dawn Games', description: 'Dawn Upon Us is an open-world military experience in development at Dawn Games. Explore its world artwork, project information and development updates.', active: 'Games', hero: true, body: `<section class="hero game-hero">${heroImage()}<div class="container hero-content">${eyebrow('Dawn Games presents · In development')}<h1>DAWN<br>UPON US<span>.</span></h1><p class="hero-copy">${esc(game.description)}</p><div class="actions">${btn('#gallery', 'Explore the world')}${btn('/news/', 'Follow development', true)}</div></div><div class="hero-bottom container"><a class="scroll-cue" href="#project"><span aria-hidden="true">↓</span> A closer look</a><span class="media-credit">${esc(site.hero.caption)}</span></div></section><section class="section project-brief" id="project"><div class="container"><div class="section-heading"><div>${eyebrow('The project')}<h2>ONE ISLAND.<br>A WORLD TAKING SHAPE.</h2></div><p class="section-intro">Exploration, atmosphere and tactical gameplay. An independent project being built and refined in Unity.</p></div>${info()}${developmentNote()}</div></section>${gallery()}<section class="section world-section" id="world"><div class="container"><div class="section-heading"><div>${eyebrow('Inside the fiction')}<h2>TWO SIDES.<br>ONE ISLAND.</h2></div><p class="section-intro">Discover the two perspectives behind the world of Dawn Upon Us.</p></div><div class="world-grid"><article><span class="caption">The occupation</span><h3>The Watch</h3><p>They arrived promising order, and never left. Read the fictional official record of how the island was “saved.”</p>${link('/the-watch.html', 'Read the record')}</article><article><span class="caption">The resistance</span><h3>The Dawn</h3><p>Not an army. An idea. Survivors who refused to give up, passing hope hand to hand.</p>${link('/the-dawn.html', 'Read their story')}</article></div></div></section>${game.trailer ? `<section class="section container" id="trailer"><h2>Official trailer</h2><video class="trailer" controls preload="none" poster="${esc(game.image)}"><source src="${esc(game.trailer)}" type="video/mp4"></video></section>` : ''}${game.store ? `<section class="section container">${btn(game.store, 'Visit the official store')}</section>` : ''}${updates()}<section class="contact-band"><div class="container"><div>${eyebrow('Follow the development')}<h2>BE PART OF<br>THE CONVERSATION.</h2></div>${btn(site.discord, 'Join our Discord')}</div></section>` });
page({ route: '/about/', title: 'About the Studio | Dawn Games', description: 'Meet Dawn Games LLC, an independent game development studio focused on atmosphere, exploration and player freedom.', active: 'About', body: intro('The studio', 'INDEPENDENT.<br>BY DESIGN<span class="orange">.</span>', 'Dawn Games is building immersive games and digital experiences, one considered step at a time.') + `<section class="section about-story"><div class="container studio-layout"><div class="statement">BUILD SOMETHING<br>YOU WANT TO<br><span class="orange">COME BACK TO.</span></div><div class="studio-copy"><h2>About Dawn Games</h2><p class="lead">An independent studio.<br>A deliberate next chapter.</p><p>Dawn Games LLC is focused on building immersive digital experiences with an emphasis on atmosphere, exploration and player freedom.</p><p>Our earlier mobile games and software projects gave us room to experiment. Today, Dawn Upon Us is our flagship: an open-world military experience in active development.</p><p>We’re building in the open, learning through iteration and sharing the work as it takes shape.</p>${link('/games/dawn-upon-us/', 'Discover Dawn Upon Us')}</div></div></section><section class="section container"><div class="section-heading"><div>${eyebrow('What guides the work')}<h2>LESS NOISE.<br>MORE INTENT.</h2></div></div>${principles()}</section>${portfolio()}${contactBand()}` });
page({ route: '/news/', title: 'News & Development Updates | Dawn Games', description: 'Read Dawn Games development updates and follow the making of Dawn Upon Us. Original development notes from the studio archive.', active: 'News', body: intro('News & development', 'THE WORLD<br>IN PROGRESS<span class="orange">.</span>', 'Notes from the build. Decisions, progress and the work behind Dawn Upon Us.') + `<section class="section news-list container"><div class="archive-notice"><span class="caption">Development archive</span><p>These original entries reflect the build at the time they were written, not a current feature list or release promise. New studio and development news will appear here when ready.</p></div>${newsCards(news)}</section>${contactBand()}` });
for (const item of news) {
  const archiveNote = item.archived ? '<aside class="archive-notice"><p>From the development archive. This entry describes an earlier build and is not a confirmation of current features or release plans.</p></aside>' : '';
  page({ route: `/news/${item.slug}/`, title: `${item.title} | Dawn Games`, description: item.summary, active: 'News', article: item, body: `<article class="article-page container"><a class="text-link" href="/news/">← All updates</a><div class="news-meta"><span>${esc(item.category)} · ${esc(item.game || site.name)}</span>${date(item)}</div><h1>${esc(item.title)}</h1>${archiveNote}${item.image ? `<img class="article-hero" src="${esc(item.image)}" alt="${esc(item.title)}" width="1600" height="900">` : ''}<div class="prose">${item.body}</div>${item.gallery.length ? `<div class="gallery-grid">${item.gallery.map(img => `<figure><a class="gallery-trigger" data-gallery="article" href="${esc(img.src)}" data-caption="${esc(img.caption)}" data-alt="${esc(img.alt)}"><img src="${esc(img.src)}" alt="${esc(img.alt)}" width="1600" height="900" loading="lazy"></a><figcaption>${esc(img.caption)}</figcaption></figure>`).join('')}</div>` : ''}<div class="article-end">${link(item.game ? game.path : '/about/', item.game ? 'Current project information' : 'About the studio')}</div></article>` });
}
page({ route: '/contact/', title: 'Contact | Dawn Games', description: 'Contact Dawn Games for general questions, business enquiries, press and creator conversations. Connect directly with the studio.', active: 'Contact', body: intro('Contact the studio', 'LET’S START<br>A CONVERSATION<span class="orange">.</span>', 'A question, an opportunity, or a story to tell. We’d like to hear from you.') + `<section class="section contact-section container"><div class="contact-main">${eyebrow('Direct to the studio')}<a class="contact-email" href="mailto:${esc(site.email)}">dawngames@<wbr>dawngamesapp.com ${arrow}</a><p>One inbox for the studio. Choose a subject below to help us understand your enquiry.</p><div class="contact-options">${[['General', 'Questions about our games or the studio.'], ['Business', 'Professional enquiries and opportunities.'], ['Press / Creator', 'Coverage, interviews and creator enquiries.']].map(([label, description]) => `<a class="contact-option" href="mailto:${site.email}?subject=${encodeURIComponent(`${label} enquiry — Dawn Games`)}"><span><strong>${label}</strong><small>${description}</small></span>${arrow}</a>`).join('')}</div><p class="caption contact-note">Opens your email app. No form data is collected by this page.</p></div><aside class="contact-aside">${eyebrow('Community')}<h2>Follow along.<br>Join in.</h2><p>Connect with Dawn Games and follow the development conversation.</p>${link(site.discord, 'Join our Discord')}<div class="contact-divider"></div>${eyebrow('Press & creators')}<p>For current project information, start with the Dawn Upon Us development page.</p>${link(game.path, 'View the project')}</aside></section>` });
page({ route: '/projects/', title: 'Apps & Experiments | Dawn Games', description: 'Explore earlier Dawn Games projects, including Block Drop DG, Darknet Idle and Hacker: Day in the Life.', active: 'Games', body: intro('Apps & experiments', 'WHERE IDEAS<br>TAKE SHAPE<span class="orange">.</span>', 'Our earlier games and digital projects. A continuing part of the studio’s story, alongside Dawn Upon Us.') + `<section class="section container">${projectCards(projects.filter(p => p.kind !== 'flagship'))}</section>${contactBand()}` });

// Preserve the original product information and product-specific legal text.
// CSS is scoped using native nesting so it cannot restyle the studio navigation.
for (const p of projects.filter(p => p.kind !== 'flagship')) {
  let body = legacy[p.slug].body.replace(/src="screenshot_(\d)\.png"/g, 'src="/assets/media/app-screen-$1.webp" loading="lazy" width="585" height="1300"');
  body = body.replace(/<section id="screenshots">[\s\S]*?<\/section>/g, section => section.includes('class="screenshot-placeholder"') ? '<span id="screenshots"></span>' : section);
  body = body.replace(/class="screenshots-scroll"/g, 'class="screenshots-scroll" tabindex="0" role="region" aria-label="Game screenshots, scroll horizontally"');
  body = body.replace(/href="index.html"/g, 'href="/"').replace(/href="games.html"/g, 'href="/games/"').replace(/href="apps.html"/g, 'href="/projects/"').replace(/href="devlog.html"/g, 'href="/news/"');
  if (p.slug === 'beamer-connect') body = body.replace('The easiest, safest BMW companion app.', 'Beamer Connect.').replace('Follow the build →', 'Studio updates →');
  body = body.replace(/target="_blank"(?!\s+rel)/g, 'target="_blank" rel="noopener noreferrer"');
  const css = `.legacy-content { ${legacy[p.slug].css} }`;
  page({ route: p.path, title: `${p.title} | Dawn Games Projects`, description: p.description, active: 'Games', css, body: `<div class="legacy-context container"><a href="/projects/">← Apps & experiments</a><span>From the Dawn Games portfolio</span></div><div class="legacy-content">${body}</div>` });
}
for (const name of ['the-watch', 'the-dawn']) {
  const title = name === 'the-watch' ? 'The Watch' : 'The Dawn';
  page({ route: `/${name}.html`, title: `${title} | The World of Dawn Upon Us`, description: `Read the fictional ${title === 'The Watch' ? 'official record of The Watch' : 'resistance account of The Dawn'} from the world of Dawn Upon Us.`, active: 'Games', body: `<article class="article-page lore-page container"><a class="text-link" href="${game.path}#world">← Back to the world</a>${eyebrow('Dawn Upon Us · Fictional world lore')}<h1>${title.toUpperCase()}<span class="orange">.</span></h1><p class="lore-note">In-world fiction, told from the perspective of this faction. Not a statement from Dawn Games.</p><div class="prose">${legacy[name].body.replace(/src="assets\//g, 'src="/assets/').replace(/<img /g, '<img decoding="async" ')}</div><div class="article-end">${link(name === 'the-watch' ? '/the-dawn.html' : '/the-watch.html', 'Read the other perspective')}</div></article>` });
}
page({ route: '/privacy.html', title: 'Website & Game Privacy | Dawn Games', description: 'Website privacy information and the existing Dawn Games mobile-game privacy policy, including contact and third-party services.', body: intro('Privacy', 'YOUR VISIT.<br>OUR RESPONSIBILITY.', 'Website information and the existing published privacy policy for our mobile games.') + `<article class="prose legal container"><h2>Website privacy</h2><p>This website provides studio and project information without an account or a contact-form database. Email links open your email application; information you send by email is received by the studio.</p><p>The production website retains its existing GoatCounter page-visit analytics. It loads a script from gc.zgo.at and sends page-visit information to dawngamesapp.goatcounter.com. See <a href="https://www.goatcounter.com/privacy" target="_blank" rel="noopener noreferrer">GoatCounter’s privacy information</a> for how the provider processes visits. The local review site does not load analytics.</p><p>Our site is served by its existing hosting provider. Visiting external Discord, store and privacy-policy links takes you to those providers, whose own policies apply. No new analytics or advertising scripts have been added to this redesign.</p><hr><h2>Published mobile-game privacy policy</h2><p>The following is the existing game policy, retained separately from this website’s privacy information. Individual game pages also preserve their product-specific policies.</p>${legacy.privacy.body.replace(/target="_blank"(?!\s+rel)/g, 'target="_blank" rel="noopener noreferrer"')}</article>` });
page({ route: '/404.html', title: 'Page Not Found | Dawn Games', description: 'This page could not be found. Return to Dawn Games or explore Dawn Upon Us.', noindex: true, body: intro('Page not found', 'A TURN<br>OFF THE MAP.', 'The page you’re looking for may have moved. Let’s get you back to the studio.') + `<div class="container error-actions">${btn('/', 'Return home')}${btn('/games/', 'Explore our games', true)}</div>` });

// Existing inbound URLs continue to resolve, including old in-page fragments.
for (const [old, target] of Object.entries({ '/games.html': '/games/', '/apps.html': '/projects/', '/dawn-upon-us.html': game.path, '/devlog.html': '/news/', '/just-right.html': '/projects/', '/beamer-connect.html': '/projects/' })) {
  fs.writeFileSync(path.join(root, old.slice(1)), `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Page moved | Dawn Games</title><meta http-equiv="refresh" content="0;url=${target}"><link rel="canonical" href="${site.origin}${target}"><meta name="robots" content="noindex,follow"><script src="/assets/js/redirect.js" defer data-target="${target}"></script></head><body><p>This page has moved. <a href="${target}">Continue to Dawn Games</a>.</p></body></html>\n`);
}
fs.writeFileSync(path.join(root, 'sitemap.xml'), `<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${routes.map(route => `<url><loc>${site.origin}${route}</loc></url>`).join('')}</urlset>\n`);
fs.writeFileSync(path.join(root, 'robots.txt'), `User-agent: *\nAllow: /\nDisallow: /menu-mockup.html\nDisallow: /tools/\nDisallow: /tests/\nDisallow: /_review/\nSitemap: ${site.origin}/sitemap.xml\n`);
fs.writeFileSync(path.join(root, 'site.webmanifest'), JSON.stringify({ name: site.company, short_name: site.name, start_url: '/', display: 'browser', background_color: '#050505', theme_color: '#050505', icons: [{ src: '/favicon-192.png', sizes: '192x192', type: 'image/png' }] }, null, 2) + '\n');
fs.writeFileSync(path.join(root, '_content/routes.json'), JSON.stringify(routes, null, 2) + '\n');
console.log(`Built ${routes.length} indexable pages, 6 compatibility routes and 404. No deployment performed.`);
